services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - '9094:9094'
    env_file:
      - .env

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    ports:
      - '5173:80'
    env_file:
      - .env
