services:
  ui:
    image: ghcr.io/lecca-digital/lecca-io/ui:main
    container_name: lecca-io-ui
    restart: unless-stopped
    ports:
      - '5173:80'
    env_file:
      - .env

  server:
    image: ghcr.io/lecca-digital/lecca-io/server:main
    container_name: lecca-io-server
    restart: unless-stopped
    ports:
      - '9094:9094'
    env_file:
      - .env
    networks:
      - lecca
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}

  postgres:
    container_name: lecca-io-db
    image: postgres:17
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lecca
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  lecca:

volumes:
  postgres_data:
