name: Create Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run (no actual release)'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            release-deps-package.json

      - name: Create package.json for release dependencies
        run: |
          echo '{"dependencies": {
            "semantic-release": "latest",
            "@semantic-release/changelog": "latest",
            "@semantic-release/git": "latest",
            "@semantic-release/github": "latest",
            "@semantic-release/npm": "latest"
          }}' > release-deps-package.json

      - name: Install semantic-release packages
        run: npm install --no-package-lock --prefix . --package-lock-only=false --no-save

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ inputs.dryRun }}
        run: npx semantic-release
